import torch

DATA_PATH = "/scratch/DL24FA"

BALL_CNN_CHANNEL_SIZES = [4,16,64]
BALL_CNN_OUT_DIM = 2
BALL_CNN_POOL_SIZE = 4
BALL_CNN_KERNEL_SIZE = 3
BALL_CNN_FINAL_ACTIVATION = torch.sigmoid

BORDER_CNN_CHANNEL_SIZES = [8,32,128]
BORDER_CNN_OUT_DIM = 4
BORDER_CNN_POOL_SIZE = 4
BORDER_CNN_KERNEL_SIZE = 3
BORDER_CNN_FINAL_ACTIVATION = torch.tanh

PRED_LAYER_SIZES = [
    BALL_CNN_OUT_DIM + BORDER_CNN_OUT_DIM + 2,
    32,
    1
]
PRED_FINAL_ACTIVATION = torch.sigmoid